# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CreateStdDistancePointers <- function(types, considerNaNs) {
    .Call('_kohonenBEAMM_CreateStdDistancePointers', PACKAGE = 'kohonenBEAMM', types, considerNaNs)
}

CreateStdDistancePointer <- function(type, considerNaNs) {
    .Call('_kohonenBEAMM_CreateStdDistancePointer', PACKAGE = 'kohonenBEAMM', type, considerNaNs)
}

ObjectDistances <- function(data, numVars, numNAs, distanceFunctions, weights) {
    .Call('_kohonenBEAMM_ObjectDistances', PACKAGE = 'kohonenBEAMM', data, numVars, numNAs, distanceFunctions, weights)
}

RcppSupersom <- function(data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, alphas, radii, numEpochs) {
    .Call('_kohonenBEAMM_RcppSupersom', PACKAGE = 'kohonenBEAMM', data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, alphas, radii, numEpochs)
}

RcppBatchSupersom <- function(data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs) {
    .Call('_kohonenBEAMM_RcppBatchSupersom', PACKAGE = 'kohonenBEAMM', data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs)
}

RcppParallelBatchSupersom <- function(data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs, numCores) {
    .Call('_kohonenBEAMM_RcppParallelBatchSupersom', PACKAGE = 'kohonenBEAMM', data, codes, numVars, weights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs, numCores)
}

RcppWeightedBatchSupersom <- function(data, codes, numVars, weights, obsWeights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs) {
    .Call('_kohonenBEAMM_RcppWeightedBatchSupersom', PACKAGE = 'kohonenBEAMM', data, codes, numVars, weights, obsWeights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs)
}

RcppWeightedParallelBatchSupersom <- function(data, codes, numVars, weights, obsWeights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs, numCores) {
    .Call('_kohonenBEAMM_RcppWeightedParallelBatchSupersom', PACKAGE = 'kohonenBEAMM', data, codes, numVars, weights, obsWeights, distanceFunctions, numNAs, neighbourhoodDistances, neighbourhoodFct, radii, numEpochs, numCores)
}

RcppMap <- function(data, numVars, numNAs, codes, weights, distanceFunctions) {
    .Call('_kohonenBEAMM_RcppMap', PACKAGE = 'kohonenBEAMM', data, numVars, numNAs, codes, weights, distanceFunctions)
}

